# pod 수 세기
kubectl get pods --no-headers | wc -l

# label이 있는 pod 수 세기
kubectl get pods --selector env=dev --no-headers | wc -l

# finance business unit(bu)가 있는 pod 수 세기
kubectl get pods --selector bu=finance --no-headers | wc -l

# How many objects are in the prod environment including PODs, ReplicaSets and any other objects?
kubectl get all --selector env=prod --no-headers | wc -l

# 여러 라벨을 붙여서 공통된 pod 조회
kubectl get pod --selector bu=finance,env=prod,ti
er=frontend

# vi 세팅
: set paste
: set nu
: set ts=2
: set sw=2
: set ai

# replicaset 수정
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicaset-1
spec:
   replicas: 2
   selector:
      matchLabels:
        tier: nginx
   template:
     metadata:
       labels:
        tier: nginx
     spec:
       containers:
       - name: nginx
         image: nginx